// Działy i wymagania szczegółowe z podstawy programowej (biologia PR, chemia PR).
// Wygenerowane z project/plan-data.json — kształt: { num, title, groups: [{ label, points: [] }] }.
window.PLANER_DZIALY = {
  bio: [
    { num: "I", title: "Chemizm życia", groups: [
      { label: "Składniki nieorganiczne", points: [
        "przedstawia znaczenie biologiczne makroelementów, w tym pierwiastków biogennych",
        "przedstawia znaczenie biologiczne wybranych mikroelementów (Fe, I, F)",
        "wyjaśnia rolę wody w życiu organizmów, z uwzględnieniem jej właściwości fizycznych i chemicznych",
      ] },
      { label: "Składniki organiczne", points: [
        "przedstawia budowę węglowodanów (uwzględniając wiązania glikozydowe α, β); rozróżnia monosacharydy (glukoza, fruktoza, galaktoza, ryboza, deoksyryboza), disacharydy (sacharoza, laktoza, maltoza), polisacharydy (skrobia, glikogen, celuloza, chityna) i określa znaczenie biologiczne węglowodanów, uwzględniając ich właściwości fizyczne i chemiczne; planuje oraz przeprowadza doświadczenie wykazujące obecność skrobi (polisacharydów) w materiale biologicznym",
        "przedstawia budowę białek (uwzględniając wiązania peptydowe); rozróżnia białka proste i złożone; opisuje strukturę I-, II-, III- i IV-rzędową białek; przedstawia wpływ czynników fizycznych i chemicznych na białko (zjawisko koagulacji i denaturacji); określa biologiczne znaczenie białek (albuminy, globuliny, histony, kolagen, keratyna, hemoglobina, mioglobina); przeprowadza obserwacje wpływu wybranych czynników fizycznych i chemicznych na białko",
        "przedstawia budowę lipidów (uwzględniając wiązania estrowe); rozróżnia lipidy proste i złożone, przedstawia właściwości lipidów oraz określa ich znaczenie biologiczne",
        "porównuje skład chemiczny i strukturę cząsteczek DNA i RNA, z uwzględnieniem rodzajów wiązań występujących w tych cząsteczkach; określa znaczenie biologiczne kwasów nukleinowych",
      ] },
    ] },
    { num: "II", title: "Komórka", groups: [
      { label: null, points: [
        "rozpoznaje elementy budowy komórki eukariotycznej na preparacie mikroskopowym, na mikrofotografii, rysunku lub na schemacie",
        "wykazuje związek budowy błony komórkowej z pełnionymi przez nią funkcjami",
        "rozróżnia rodzaje transportu do i z komórki (dyfuzja prosta i wspomagana, transport aktywny, endocytoza i egzocytoza)",
        "wyjaśnia rolę błony komórkowej i tonoplastu w procesach osmotycznych; planuje i przeprowadza doświadczenie wykazujące zjawisko osmozy wywołane różnicą stężeń wewnątrz i na zewnątrz komórki; planuje i przeprowadza obserwację zjawiska plazmolizy",
        "przedstawia budowę jądra komórkowego i jego rolę w funkcjonowaniu komórki",
        "opisuje budowę rybosomów, ich powstawanie i pełnioną funkcję oraz określa ich lokalizację w komórce",
        "przedstawia błony wewnątrzkomórkowe jako zintegrowany system strukturalno-funkcjonalny oraz określa jego rolę w kompartmentacji komórki",
        "opisuje budowę mitochondriów i plastydów ze szczególnym uwzględnieniem chloroplastów; dokonuje obserwacji mikroskopowych plastydów w materiale biologicznym",
        "przedstawia argumenty przemawiające za endosymbiotycznym pochodzeniem mitochondriów i chloroplastów",
        "wykazuje związek budowy ściany komórkowej z pełnioną funkcją oraz wskazuje grupy organizmów, u których ona występuje",
        "przedstawia znaczenie wakuoli w funkcjonowaniu komórki roślinnej",
        "przedstawia znaczenie cytoszkieletu w ruchu komórek, transporcie wewnątrzkomórkowym, podziałach komórkowych oraz stabilizacji struktury komórki; dokonuje obserwacji mikroskopowych ruchów cytoplazmy w komórkach roślinnych",
        "wykazuje różnice w budowie komórki prokariotycznej i eukariotycznej",
        "wykazuje różnice w budowie komórki roślinnej, grzybowej i zwierzęcej",
      ] },
    ] },
    { num: "III", title: "Energia i metabolizm", groups: [
      { label: "Podstawowe zasady metabolizmu", points: [
        "wyjaśnia, na przykładach, pojęcia: szlaku i cyklu metabolicznego",
        "porównuje istotę procesów anabolicznych i katabolicznych oraz wykazuje, że są ze sobą powiązane",
      ] },
      { label: "Przenośniki energii oraz protonów i elektronów w komórce", points: [
        "wykazuje związek budowy ATP z jego rolą biologiczną",
        "przedstawia znaczenie NAD+, FAD, NADP+ w procesach utleniania i redukcji",
      ] },
      { label: "Enzymy", points: [
        "przedstawia charakterystyczne cechy budowy enzymu",
        "wyjaśnia, na czym polega swoistość substratowa enzymu oraz opisuje katalizę enzymatyczną",
        "przedstawia sposoby regulacji aktywności enzymów (aktywacja, inhibicja)",
        "wyjaśnia mechanizm sprzężenia zwrotnego ujemnego jako sposobu regulacji przebiegu szlaków metabolicznych",
        "wyjaśnia wpływ czynników fizykochemicznych (temperatury, pH, stężenia substratu) na przebieg katalizy enzymatycznej; planuje i przeprowadza doświadczenie badające wpływ różnych czynników na aktywność enzymów (katalaza, proteinaza)",
      ] },
      { label: "Fotosynteza", points: [
        "wykazuje związek budowy chloroplastu z przebiegiem procesu fotosyntezy",
        "przedstawia rolę barwników i fotosystemów w procesie fotosyntezy",
        "analizuje na podstawie schematu przebieg fazy zależnej od światła oraz fazy niezależnej od światła; wyróżnia substraty i produkty obu faz; wykazuje rolę składników siły asymilacyjnej w fazie niezależnej od światła",
        "wyjaśnia mechanizm powstawania ATP w procesie chemiosmozy w chloroplaście",
        "opisuje (porównuje) na podstawie schematu fotofosforylację cykliczną i niecykliczną",
      ] },
      { label: "Pozyskiwanie energii użytecznej biologicznie", points: [
        "wykazuje związek budowy mitochondrium z przebiegiem procesu oddychania komórkowego",
        "analizuje na podstawie schematu przebieg glikolizy, reakcji pomostowej i cyklu Krebsa, wyróżnia substraty i produkty tych procesów",
        "przedstawia, na czym polega fosforylacja substratowa",
        "wyjaśnia mechanizm powstawania ATP w procesie chemiosmozy w mitochondriach (fosforylacja oksydacyjna)",
        "porównuje drogi przemiany pirogronianu w fermentacji alkoholowej, mleczanowej i w oddychaniu tlenowym",
        "wyjaśnia, dlaczego utlenianie substratu energetycznego w warunkach tlenowych dostarcza więcej energii niż w warunkach beztlenowych",
        "analizuje na podstawie schematu przebieg glukoneogenezy i glikogenolizy oraz wykazuje związek tych procesów z pozyskiwaniem energii przez komórkę",
      ] },
    ] },
    { num: "IV", title: "Podziały komórkowe", groups: [
      { label: null, points: [
        "przedstawia organizację materiału genetycznego w komórce",
        "wyjaśnia mechanizm replikacji DNA, z uwzględnieniem roli enzymów (helikaza, prymaza, polimeraza DNA, ligaza)",
        "opisuje cykl komórkowy, z uwzględnieniem zmian ilości DNA w poszczególnych jego etapach; uzasadnia konieczność replikacji DNA przed podziałem komórki",
        "opisuje przebieg kariokinezy podczas mitozy i mejozy",
        "rozpoznaje (na preparacie mikroskopowym, na schemacie, rysunku, mikrofotografii) poszczególne etapy mitozy i mejozy",
        "przedstawia znaczenie mitozy i mejozy w zachowaniu ciągłości życia na Ziemi",
        "wyjaśnia znaczenie procesu crossing-over i niezależnej segregacji chromosomów jako źródeł zmienności rekombinacyjnej i różnorodności biologicznej",
        "przedstawia apoptozę jako proces warunkujący prawidłowy rozwój i funkcjonowanie organizmów wielokomórkowych",
        "porównuje przebieg cytokinezy w komórkach roślinnych i zwierzęcych",
      ] },
    ] },
    { num: "V", title: "Zasady klasyfikacji i sposoby identyfikacji organizmów", groups: [
      { label: null, points: [
        "wnioskuje na podstawie analizy kladogramów o pokrewieństwie ewolucyjnym organizmów",
        "rozróżnia na drzewie filogenetycznym grupy monofiletyczne, parafiletyczne i polifiletyczne; wykazuje, że klasyfikacja organizmów oparta jest na ich filogenezie",
        "porządkuje hierarchicznie podstawowe rangi taksonomiczne",
      ] },
    ] },
    { num: "VI", title: "Bakterie i archeowce", groups: [
      { label: null, points: [
        "przedstawia budowę komórki prokariotycznej, z uwzględnieniem różnic w budowie ściany komórkowej bakterii Gram-dodatnich i Gram-ujemnych",
        "wyjaśnia różnice między archeowcami i bakteriami; przedstawia znaczenie archeowców; przedstawia różnorodność form morfologicznych bakterii",
        "przedstawia czynności życiowe bakterii: odżywianie (chemoautotrofizm, fotoautotrofizm, heterotrofizm); oddychanie beztlenowe (denitryfikacja, fermentacja) i tlenowe; rozmnażanie",
        "wykazuje znaczenie procesów płciowych w zmienności genetycznej bakterii",
        "przedstawia znaczenie bakterii w przyrodzie i dla człowieka, w tym wywołujących choroby człowieka (gruźlica, tężec, borelioza, salmonelloza, kiła, rzeżączka)",
      ] },
    ] },
    { num: "VII", title: "Grzyby", groups: [
      { label: null, points: [
        "przedstawia różnorodność morfologiczną grzybów",
        "przedstawia czynności życiowe grzybów: odżywianie, oddychanie i rozmnażanie; planuje i przeprowadza doświadczenie wykazujące, że drożdże przeprowadzają fermentację alkoholową",
        "przedstawia porosty jako organizmy symbiotyczne",
        "przedstawia drogi zarażenia się i zasady profilaktyki chorób wywołanych przez grzyby (grzybice skóry, narządów płciowych, płuc)",
        "przedstawia znaczenie grzybów, w tym porostów, w przyrodzie i dla człowieka",
      ] },
    ] },
    { num: "VIII", title: "Protisty", groups: [
      { label: null, points: [
        "przedstawia formy morfologiczne protistów",
        "przedstawia czynności życiowe protistów: odżywianie, poruszanie się, rozmnażanie, wydalanie i osmoregulację; zakłada hodowlę protistów słodkowodnych i obserwuje wybrane czynności życiowe tych protistów",
        "wykazuje związek budowy protistów ze środowiskiem i trybem ich życia (obecność aparatu ruchu, budowa błony komórkowej, obecność chloroplastów i wodniczek tętniących)",
        "analizuje na podstawie schematów przebieg cykli rozwojowych protistów i rozróżnia poszczególne fazy jądrowe",
        "przedstawia drogi zarażenia się i zasady profilaktyki chorób wywołanych przez protisty (malaria, toksoplazmoza, lamblioza, rzęsistkowica)",
        "przedstawia znaczenie protistów (w tym prostitów fotosyntetyzujących i symbiotycznych) w przyrodzie i dla człowieka",
      ] },
    ] },
    { num: "IX", title: "Różnorodność roślin", groups: [
      { label: "Rośliny pierwotnie wodne", points: [
        "rozróżnia zielenice i krasnorosty",
        "przedstawia znaczenie krasnorostów i zielenic w przyrodzie i dla człowieka",
      ] },
      { label: "Rośliny lądowe i wtórnie wodne", points: [
        "określa różnice między warunkami życia w wodzie i na lądzie",
        "przedstawia na przykładzie rodzimych gatunków cechy charakterystyczne mchów, widłakowych, skrzypowych, paprociowych i nasiennych oraz na podstawie tych cech identyfikuje organizm jako przedstawiciela jednej z tych grup",
        "rozpoznaje tkanki roślinne na preparacie mikroskopowym, na schemacie, mikrofotografii, na podstawie opisu i wykazuje związek ich budowy z pełnioną funkcją",
        "przedstawia znaczenie połączeń międzykomórkowych w tkankach roślinnych",
        "wykazuje związek budowy morfologicznej i anatomicznej (pierwotnej i wtórnej) organów wegetatywnych roślin z pełnionymi przez nie funkcjami",
        "przedstawia cechy budowy roślin, które umożliwiły im zasiedlenie środowisk lądowych",
        "uzasadnia, że modyfikacje organów wegetatywnych roślin są adaptacją do różnych warunków środowiska i pełnionych funkcji",
        "przedstawia znaczenie roślin dla człowieka",
      ] },
      { label: "Gospodarka wodna i odżywianie mineralne roślin", points: [
        "wyjaśnia mechanizmy pobierania oraz transportu wody i soli mineralnych",
        "planuje i przeprowadza obserwację pozwalającą na identyfikację tkanki przewodzącej wodę w roślinie",
        "wykazuje związek zmian potencjału osmotycznego i potencjału wody z otwieraniem i zamykaniem szparek",
        "wykazuje wpływ czynników zewnętrznych (temperatura, światło, wilgotność, ruchy powietrza) na bilans wodny roślin; planuje i przeprowadza doświadczenie określające wpływ czynników zewnętrznych na intensywność transpiracji",
        "opisuje wpływ suszy fizjologicznej na bilans wodny rośliny",
        "podaje dostępne dla roślin formy wybranych makroelementów (N, S)",
        "przedstawia znaczenie wybranych makro- i mikroelementów (N, S, Mg, K, P) dla roślin",
      ] },
      { label: "Odżywianie się roślin", points: [
        "określa drogi, jakimi do liści docierają substraty fotosyntezy",
        "określa drogi, jakimi transportowane są produkty fotosyntezy",
        "przedstawia adaptacje w budowie anatomicznej roślin do wymiany gazowej",
        "analizuje wpływ czynników zewnętrznych i wewnętrznych na przebieg procesu fotosyntezy; planuje i przeprowadza doświadczenie wykazujące wpływ temperatury i natężenia światła na intensywność fotosyntezy",
        "przedstawia udział innych organizmów (bakterie glebowe i symbiotyczne, grzyby) w pozyskiwaniu pokarmu przez rośliny",
        "przedstawia adaptacje anatomiczne i fizjologiczne roślin typu C4 i CAM do przeprowadzania fotosyntezy w określonych warunkach środowiska",
      ] },
      { label: "Rozmnażanie i rozprzestrzenianie się roślin", points: [
        "opisuje na podstawie schematów, przemianę pokoleń mchów, paprociowych, widłakowych, skrzypowych, nagonasiennych i okrytonasiennych; (wykazuje, porównując na podstawie schematów, przemianę pokoleń mchów, paproci, nagonasiennych i okrytonasiennych, stopniową redukcję gametofitu;)",
        "przedstawia sposoby bezpłciowego rozmnażania się roślin",
        "przedstawia budowę kwiatów roślin nasiennych",
        "wykazuje związek budowy kwiatu roślin okrytonasiennych ze sposobem ich zapylania",
        "opisuje proces zapłodnienia i powstawania nasion u roślin nasiennych oraz owoców u okrytonasiennych",
        "wykazuje związek budowy owocu ze sposobem rozprzestrzeniania się roślin okrytonasiennych",
        "opisuje sposób powstawania gametofitów roślin nasiennych",
      ] },
      { label: "Wzrost i rozwój roślin", points: [
        "przedstawia budowę nasienia bielmowego (nasiona)",
        "przedstawia wpływ czynników zewnętrznych i wewnętrznych na proces kiełkowania nasion; planuje i przeprowadza doświadczenie określające wpływ wybranych czynników (woda, temperatura, światło) na proces kiełkowania nasion",
        "planuje i przeprowadza doświadczenie wykazujące rolę liścieni we wzroście i rozwoju siewki rośliny",
        "określa rolę auksyn i etylenu w procesach wzrostu i rozwoju roślin",
      ] },
      { label: "Reakcja na bodźce", points: [
        "przedstawia nastie i tropizmy jako reakcje roślin na bodźce (światło, temperatura, grawitacja, bodźce mechaniczne i chemiczne); planuje i przeprowadza doświadczenie wykazujące różnice geotropizmu korzenia i pędu (rolę stożka wzrostu w dominacji wierzchołkowej)",
        "przedstawia rolę auksyn w ruchach wzrostowych roślin",
      ] },
    ] },
    { num: "X", title: "Różnorodność zwierząt", groups: [
      { label: null, points: [
        "rozróżnia zwierzęta dwuwarstwowe i trójwarstwowe; pierwouste i wtórouste; bezżuchwowce i żuchwowce; owodniowce i bezowodniowce; łożyskowe i bezłożyskowe; skrzelodyszne i płucodyszne; zmiennocieplne i stałocieplne; na podstawie drzewa filogenetycznego wykazuje pokrewieństwo między grupami zwierząt",
        "wykazuje związek trybu życia zwierząt z symetrią ich ciała (promienista i dwuboczna)",
        "wymienia cechy pozwalające na rozróżnienie parzydełkowców, płazińców, nicieni, pierścienic, mięczaków, stawonogów (skorupiaków, pajęczaków i owadów) i szkarłupni",
        "wymienia cechy pozwalające na rozróżnienie ryb, płazów, gadów, ssaków i ptaków; na podstawie tych cech identyfikuje organizm jako przedstawiciela jednej z tych grup",
      ] },
    ] },
    { num: "XI", title: "Funkcjonowanie zwierząt", groups: [
      { label: "Podstawowe zasady budowy i funkcjonowania organizmu zwierzęcego", points: [
        "rozpoznaje tkanki organizmu człowieka (zwierzęce) na preparacie mikroskopowym, na schemacie, mikrofotografii, na podstawie opisu i wykazuje związek ich budowy z pełnioną funkcją",
        "przedstawia znaczenie połączeń międzykomórkowych w tkankach zwierzęcych",
        "wykazuje związek budowy narządów z pełnioną przez nie funkcją",
        "przedstawia powiązania funkcjonalne między narządami w obrębie układu",
        "przedstawia powiązania funkcjonalne między układami narządów w obrębie organizmu",
        "przedstawia mechanizmy warunkujące homeostazę (termoregulacja, osmoregulacja, stałość składu płynów ustrojowych, ciśnienie krwi)",
        "wykazuje związek między wielkością, aktywnością życiową, temperaturą ciała, a zapotrzebowaniem energetycznym organizmu. 11 2. Porównanie poszczególnych czynności życiowych zwierząt, z uwzględnieniem struktur odpowiedzialnych za ich przeprowadzanie",
      ] },
      { label: "Porównanie poszczególnych czynności życiowych zwierząt, z uwzględnieniem struktur odpowiedzialnych za ich przeprowadzanie", points: [
        "Odżywianie się",
        "Odporność",
        "Wymiana gazowa i krążenie",
        "Wydalanie i osmoregulacja",
        "Regulacja hormonalna",
        "Regulacja nerwowa",
        "Poruszanie się",
        "Pokrycie ciała i termoregulacja",
        "Rozmnażanie i rozwój",
      ] },
    ] },
    { num: "XII", title: "Wirusy", groups: [
      { label: null, points: [
        "przedstawia budowę wirusów jako bezkomórkowych form infekcyjnych",
        "przedstawia różnorodność morfologiczną i genetyczną wirusów",
        "wykazuje związek budowy wirusów ze sposobem infekowania komórek",
        "porównuje cykle infekcyjne wirusów (lityczny i lizogeniczny)",
        "wyjaśnia mechanizm odwrotnej transkrypcji i jego znaczenie w namnażaniu retrowirusów",
        "przedstawia drogi rozprzestrzeniania się i zasady profilaktyki chorób człowieka wywoływanych przez wirusy (wścieklizna, AIDS, schorzenia wywołane zakażeniem HPV, grypa, odra, ospa, różyczka, świnka, WZW typu A, B i C)",
        "przedstawia znaczenie wirusów w przyrodzie i dla człowieka",
      ] },
    ] },
    { num: "XIII", title: "Ekspresja informacji genetycznej", groups: [
      { label: null, points: [
        "porównuje strukturę genu organizmu prokariotycznego i eukariotycznego",
        "opisuje proces transkrypcji, z uwzględnieniem roli polimerazy RNA",
        "opisuje proces obróbki potranskrypcyjnej u organizmów eukariotycznych",
        "przedstawia cechy kodu genetycznego",
        "opisuje proces translacji i przedstawia znaczenie modyfikacji potranslacyjnej białek",
        "porównuje przebieg ekspresji informacji genetycznej w komórce prokariotycznej i eukariotycznej",
        "przedstawia istotę regulacji ekspresji genów u organizmów eukariotycznych",
      ] },
    ] },
    { num: "XIV", title: "Genetyka klasyczna", groups: [
      { label: "Dziedziczenie cech", points: [
        "zapisuje i analizuje krzyżówki (w tym krzyżówki testowe) oraz określa prawdopodobieństwo wystąpienia określonych genotypów i fenotypów oraz stosunek fenotypowy w pokoleniach potomnych, w tym cech warunkowanych przez allele wielokrotne",
        "przedstawia dziedziczenie jednogenowe, dwugenowe i wielogenowe (dominacja pełna, dominacja niepełna, kodominacja, współdziałanie dwóch lub większej liczby genów)",
        "przedstawia główne założenia chromosomowej teorii dziedziczności Morgana",
        "analizuje dziedziczenie cech sprzężonych; oblicza odległość między genami; na podstawie odległości między genami określa kolejność ich ułożenia na chromosomie",
        "wyjaśnia istotę dziedziczenia pozajądrowego",
        "przedstawia determinację oraz dziedziczenie płci",
        "przedstawia dziedziczenie cech sprzężonych z płcią",
        "analizuje rodowody i na ich podstawie ustala sposób dziedziczenia danej cechy",
      ] },
      { label: "Zmienność organizmów", points: [
        "opisuje zmienność jako różnorodność fenotypową osobników w populacji",
        "przedstawia typy zmienności genetycznej (rekombinacyjna i mutacyjna)",
        "rozróżnia ciągłą i nieciągłą zmienność cechy; wyjaśnia genetyczne podłoże tych zmienności",
        "przedstawia źródła zmienności rekombinacyjnej",
        "przedstawia rodzaje mutacji genowych oraz określa ich skutki",
        "przedstawia rodzaje aberracji chromosomowych (strukturalnych i liczbowych) oraz określa ich skutki",
        "określa na podstawie analizy rodowodu lub kariotypu podłoże genetyczne chorób człowieka (mukowiscydoza, fenyloketonuria, pląsawica Huntingtona, hemofilia, daltonizm, zespół Klinefeltera, zespół Turnera, zespół Downa)",
        "wykazuje związek między narażeniem organizmu na działanie czynników mutagennych (fizycznych, chemicznych, biologicznych) a zwiększonym ryzykiem wystąpienia chorób",
        "przedstawia transformację nowotworową komórek jako następstwo mutacji w obrębie genów kodujących białka regulujące cykl komórkowy oraz odpowiedzialnych za naprawę DNA",
      ] },
    ] },
    { num: "XV", title: "Biotechnologia. Podstawy inżynierii genetycznej", groups: [
      { label: null, points: [
        "rozróżnia biotechnologię tradycyjną i molekularną",
        "przedstawia współczesne zastosowania metod biotechnologii tradycyjnej w przemyśle farmaceutycznym, spożywczym, rolnictwie, biodegradacji i oczyszczaniu ścieków",
        "przedstawia narzędzia wykorzystywane w biotechnologii molekularnej (enzymy: polimerazy, ligazy i enzymy restrykcyjne) i określa ich zastosowania",
        "przedstawia istotę technik stosowanych w inżynierii genetycznej (hybrydyzacja DNA, analiza restrykcyjna i elektroforeza DNA, metoda PCR, sekwencjonowanie DNA metodą Sangera)",
        "przedstawia zastosowania wybranych technik inżynierii genetycznej w medycynie sądowej, kryminalistyce, diagnostyce chorób",
        "wyjaśnia, czym jest organizm transgeniczny i GMO; przedstawia sposoby otrzymywania organizmów transgenicznych",
        "przedstawia potencjalne korzyści i zagrożenia wynikające z zastosowania organizmów modyfikowanych genetycznie w rolnictwie, przemyśle, medycynie i badaniach naukowych; podaje przykłady produktów otrzymanych z wykorzystaniem modyfikowanych genetycznie organizmów",
        "opisuje klonowanie organizmów metodą transferu jąder komórkowych i metodą rozdziału komórek zarodka na wczesnych etapach jego rozwoju oraz przedstawia zastosowania tych metod",
        "przedstawia sposoby otrzymywania i pozyskiwania komórek macierzystych oraz ich zastosowania w medycynie",
        "przedstawia sytuacje, w których zasadne jest korzystanie z poradnictwa genetycznego",
        "przedstawia ogólną zasadę działania terapii genowej",
        "przedstawia szanse i zagrożenia wynikające z zastosowań biotechnologii molekularnej",
        "dyskutuje o problemach społecznych i etycznych związanych z rozwojem inżynierii genetycznej oraz formułuje własne opinie w tym zakresie",
        "przedstawia zastosowania biotechnologii molekularnej w badaniach ewolucyjnych i systematyce organizmów",
      ] },
    ] },
    { num: "XVI", title: "Ewolucja", groups: [
      { label: null, points: [
        "przedstawia podstawowe źródła wiedzy o mechanizmach i przebiegu ewolucji",
        "określa pokrewieństwo ewolucyjne gatunków na podstawie analizy drzewa filogenetycznego",
        "przedstawia rodzaje zmienności i wykazuje znaczenie zmienności genetycznej w procesie ewolucji",
        "wyjaśnia mechanizm działania doboru naturalnego i przedstawia jego rodzaje (stabilizujący, kierunkowy i różnicujący)",
        "wykazuje, że dzięki doborowi naturalnemu organizmy zyskują nowe cechy adaptacyjne",
        "określa warunki, w jakich zachodzi dryf genetyczny",
        "przedstawia przyczyny zmian częstości alleli w populacji",
        "przedstawia założenia prawa Hardy’ego – Weinberga",
        "stosuje równanie Hardy’ego – Weinberga do obliczenia częstości alleli, genotypów i fenotypów w populacji",
        "przedstawia gatunek jako izolowaną pulę genową",
        "przedstawia mechanizm powstawania gatunków wskutek specjacji allopatrycznej i sympatrycznej",
        "opisuje warunki, w jakich zachodzi radiacja adaptacyjna oraz ewolucja zbieżna",
        "rozpoznaje, na podstawie opisu, schematu, rysunku, konwergencję i dywergencję",
        "porządkuje chronologicznie formy kopalne człowiekowatych, wskazując na ich cechy charakterystyczne",
        "określa pokrewieństwo człowieka z innymi zwierzętami na podstawie analizy drzewa rodowego",
        "przedstawia podobieństwa między człowiekiem a innymi naczelnymi; przedstawia cechy odróżniające człowieka od małp człekokształtnych",
        "wyjaśnia, dlaczego mimo działania doboru naturalnego w populacji ludzkiej utrzymują się allele warunkujące choroby genetyczne",
        "analizuje różnorodne źródła informacji dotyczące ewolucji człowieka i przedstawia tendencje zmian ewolucyjnych",
      ] },
    ] },
    { num: "XVII", title: "Ekologia", groups: [
      { label: "Ekologia organizmów", points: [
        "rozróżnia czynniki biotyczne i abiotyczne oddziałujące na organizmy",
        "przedstawia elementy niszy ekologicznej organizmu; rozróżnia niszę ekologiczną od siedliska",
        "wyjaśnia, czym jest tolerancja ekologiczna",
        "wykazuje znaczenie organizmów o wąskim zakresie tolerancji ekologicznej w bioindykacji",
        "określa środowisko życia organizmu na podstawie jego tolerancji ekologicznej na określony czynnik",
        "przedstawia adaptacje form ekologicznych roślin do życia w różnych siedliskach",
      ] },
      { label: "Ekologia populacji", points: [
        "przedstawia istotę teorii metapopulacji oraz określa znaczenie migracji w przepływie genów dla przetrwania gatunku w środowisku",
        "charakteryzuje populację, określając jej cechy (liczebność, zagęszczenie, struktura przestrzenna, wiekowa i płciowa); dokonuje obserwacji cech populacji wybranego gatunku.",
      ] },
      { label: "Ekologia ekosystemu", points: [
        "wyjaśnia znaczenie zależności nieantagonistycznych (mutualizm obligatoryjny i fakultatywny, komensalizm) w ekosystemie i podaje ich przykłady",
        "przedstawia skutki konkurencji wewnątrzgatunkowej i międzygatunkowej",
        "wyjaśnia zmiany liczebności populacji w układzie zjadający i zjadany",
        "przedstawia adaptacje drapieżników, pasożytów i roślinożerców do zdobywania pokarmu",
        "przedstawia adaptacje obronne ofiar drapieżników, żywicieli pasożytów oraz zjadanych roślin",
        "określa zależności pokarmowe w ekosystemie na podstawie analizy fragmentów sieci pokarmowych; przedstawia zależności pokarmowe w biocenozie w postaci łańcuchów pokarmowych",
        "wyjaśnia przepływ energii i obieg materii w ekosystemie",
        "opisuje obieg węgla i azotu w przyrodzie, wykazując rolę różnych grup organizmów w tych obiegach",
        "przedstawia sukcesję jako proces przemiany ekosystemu w czasie",
      ] },
    ] },
    { num: "XVIII", title: "Różnorodność biologiczna, jej zagrożenia i ochrona", groups: [
      { label: null, points: [
        "przedstawia typy różnorodności biologicznej: genetyczną, gatunkową i ekosystemową",
        "wymienia główne czynniki geograficzne kształtujące różnorodność gatunkową i ekosystemową Ziemi (klimat, ukształtowanie powierzchni); podaje przykłady miejsc charakteryzujących się szczególnym bogactwem gatunkowym; podaje przykłady endemitów jako gatunków unikatowych dla danego miejsca regionu; wykazuje związek między rozmieszczeniem biomów a warunkami klimatycznymi na kuli ziemskiej",
        "wykazuje wpływ działalności człowieka (intensyfikacji rolnictwa, urbanizacji, industrializacji, rozwoju komunikacji i turystyki) na różnorodność biologiczną",
        "wyjaśnia znaczenie restytucji i reintrodukcji gatunków dla zachowania różnorodności biologicznej; podaje przykłady restytuowanych gatunków",
        "uzasadnia konieczność stosowania różnych form ochrony przyrody, w tym Natura 2000",
        "uzasadnia konieczność współpracy międzynarodowej (CITES, Konwencja o Różnorodności Biologicznej, Agenda",
        "dla ochrony różnorodności biologicznej",
        "przedstawia istotę zrównoważonego rozwoju",
      ] },
    ] },
  ],
  chem: [
    { num: "I", title: "Atomy, cząsteczki i stechiometria chemiczna", groups: [
      { label: null, points: [
        "stosuje pojęcia: nuklid, izotop, mol i stała Avogadra",
        "odczytuje w układzie okresowym masy atomowe pierwiastków i na ich podstawie oblicza masę molową związków chemicznych (nieorganicznych i organicznych) o podanych wzorach lub nazwach",
        "stosuje pojęcie masy atomowej (średnia masa atomów danego pierwiastka, z uwzględnieniem jego składu izotopowego)",
        "pisze równania naturalnych przemian promieniotwórczych (α, β¯) oraz sztucznych reakcji jądrowych",
        "ustala wzór empiryczny i rzeczywisty związku chemicznego (nieorganicznego i organicznego) na podstawie jego składu i masy molowej",
        "dokonuje interpretacji jakościowej i ilościowej równania reakcji w ujęciu molowym, masowym i objętościowym (dla gazów)",
        "wykonuje obliczenia, z uwzględnieniem wydajności reakcji, dotyczące: liczby moli oraz mas substratów i produktów (stechiometria wzorów i równań chemicznych), objętości gazów w warunkach normalnych, po zmieszaniu substratów w stosunku stechiometrycznym i niestechiometrycznym",
        "stosuje do obliczeń równanie Clapeyrona",
      ] },
    ] },
    { num: "II", title: "Budowa atomu", groups: [
      { label: null, points: [
        "interpretuje wartości liczb kwantowych; opisuje stan elektronu w atomie za pomocą liczb kwantowych; stosuje pojęcia: powłoka, podpowłoka, stan orbitalny, spin elektronu",
        "stosuje zasady rozmieszczania elektronów na orbitalach (zakaz Pauliego i regułę Hunda) w atomach pierwiastków wieloelektronowych",
        "pisze konfiguracje elektronowe atomów pierwiastków do Z=38 oraz ich jonów o podanym ładunku, uwzględniając przynależność elektronów do podpowłok (zapisy konfiguracji: pełne, skrócone i schematy klatkowe)",
        "określa przynależność pierwiastków do bloków konfiguracyjnych: s, p i d układu okresowego na podstawie konfiguracji elektronowej; wskazuje związek między budową elektronową atomu a położeniem pierwiastka w układzie okresowym i jego właściwościami fizycznymi (promieniem atomowym, energią jonizacji) i chemicznymi",
      ] },
    ] },
    { num: "III", title: "Wiązania chemiczne. Oddziaływania międzycząsteczkowe", groups: [
      { label: null, points: [
        "określa rodzaj wiązania: jonowe, kowalencyjne (w tym koordynacyjne), metaliczne; na podstawie elektroujemności według Paulinga określa polaryzację wiązania kowalencyjnego; (określa rodzaj wiązania (jonowe, kowalencyjne (atomowe) 2 niespolaryzowane, kowalencyjne (atomowe) spolaryzowane, donorowo- akceptorowe (koordynacyjne)) na podstawie elektroujemności oraz liczby elektronów walencyjnych atomów łączących się pierwiastków;)",
        "pisze wzory elektronowe typowych cząsteczek związków kowalencyjnych i jonów złożonych, z uwzględnieniem wolnych par elektronowych (wiązań koordynacyjnych)",
        "wyjaśnia tworzenie orbitali zhybrydyzowanych zgodnie z modelem hybrydyzacji, opisuje ich wzajemne ułożenie w przestrzeni",
        "rozpoznaje typ hybrydyzacji (sp, sp2, sp3) orbitali walencyjnych atomu centralnego w cząsteczkach związków nieorganicznych i organicznych; przewiduje budowę przestrzenną drobin metodą VSEPR; określa kształt drobin (struktura digonalna, trygonalna, tetraedryczna, piramidalna, V- kształtna)",
        "określa typ wiązania (σ i π) w cząsteczkach związków nieorganicznych i organicznych",
        "opisuje i przewiduje wpływ rodzaju wiązania (jonowe, kowalencyjne, metaliczne), oddziaływań międzycząsteczkowych (siły van der Waalsa, wiązania wodorowe) oraz kształtu drobin na właściwości fizyczne substancji nieorganicznych i organicznych; wskazuje te cząsteczki i fragmenty cząsteczek, które są polarne, oraz te, które są niepolarne",
        "porównuje właściwości fizyczne substancji tworzących kryształy jonowe, kowalencyjne, molekularne oraz metaliczne",
        "wyjaśnia pojęcie alotropii pierwiastków; na podstawie znajomości budowy diamentu, grafitu, grafenu i fullerenów tłumaczy ich właściwości i zastosowania",
      ] },
    ] },
    { num: "IV", title: "Kinetyka i statyka chemiczna. Energetyka reakcji chemicznych", groups: [
      { label: null, points: [
        "definiuje i oblicza szybkość reakcji (jako zmianę stężenia reagenta w czasie)",
        "przewiduje wpływ: stężenia (ciśnienia) substratów, obecności katalizatora, stopnia rozdrobnienia substratów i temperatury na szybkość reakcji; projektuje i przeprowadza odpowiednie doświadczenia",
        "na podstawie równania kinetycznego określa rząd reakcji względem każdego substratu; na podstawie danych doświadczalnych ilustrujących związek między stężeniem substratu a szybkością reakcji określa rząd reakcji i pisze równanie kinetyczne",
        "stosuje pojęcia: egzoenergetyczny, endoenergetyczny, energia aktywacji do opisu efektów energetycznych przemian; zaznacza wartość energii aktywacji na schemacie ilustrującym zmiany energii w reakcji egzo- i endoenergetycznej",
        "porównuje wartość energii aktywacji przebiegającej z udziałem i bez udziału katalizatora",
        "wykazuje się znajomością i rozumieniem pojęć: stan równowagi dynamicznej i stała równowagi; pisze wyrażenie na stałą równowagi danej reakcji",
        "oblicza wartość stałej równowagi reakcji odwracalnej; oblicza stężenia równowagowe albo stężenia początkowe reagentów",
        "wymienia czynniki, które wpływają na stan równowagi reakcji; wyjaśnia, dlaczego obecność katalizatora nie wpływa na wydajność przemiany; stosuje regułę Le Chateliera-Brauna (regułę przekory) do jakościowego określenia wpływu zmian temperatury, stężenia reagentów i ciśnienia na układ pozostający w stanie równowagi dynamicznej",
        "stosuje pojęcie standardowej entalpii przemiany; interpretuje zapis ΔH < 0 i ΔH > 0; określa efekt energetyczny reakcji chemicznej na podstawie wartości entalpii",
        "opisuje różnice między układem otwartym, zamkniętym i izolowanym",
      ] },
    ] },
    { num: "V", title: "Roztwory", groups: [
      { label: null, points: [
        "rozróżnia układy homogeniczne i heterogeniczne; opisuje tworzenie się emulsji",
        "wykonuje obliczenia związane z przygotowaniem, rozcieńczaniem i zatężaniem roztworów z zastosowaniem pojęć: stężenie procentowe lub molowe oraz rozpuszczalność",
        "projektuje i przeprowadza doświadczenie pozwalające otrzymać roztwór o określonym stężeniu procentowym lub molowym",
        "opisuje sposoby rozdzielenia roztworów właściwych (ciał stałych w cieczach, cieczy w cieczach) na składniki (m.in. ekstrakcja, chromatografia, elektroforeza)",
        "projektuje i przeprowadza doświadczenie pozwalające rozdzielić mieszaninę niejednorodną (ciał stałych w cieczach) na składniki",
      ] },
    ] },
    { num: "VI", title: "Reakcje w roztworach wodnych", groups: [
      { label: null, points: [
        "pisze równania dysocjacji elektrolitycznej związków nieorganicznych i organicznych, z uwzględnieniem dysocjacji stopniowej",
        "stosuje termin stopień dysocjacji dla ilościowego opisu zjawiska dysocjacji elektrolitycznej",
        "interpretuje wartości pKw, pH, Ka, Kb, Ks",
        "wykonuje obliczenia z zastosowaniem pojęć: stała dysocjacji, stopień dysocjacji, pH, iloczyn jonowy wody, iloczyn rozpuszczalności; stosuje do obliczeń prawo rozcieńczeń Ostwalda",
        "porównuje moc elektrolitów na podstawie wartości ich stałych dysocjacji",
        "przewiduje odczyn roztworu po reakcji substancji zmieszanych w ilościach stechiometrycznych i niestechiometrycznych",
        "klasyfikuje substancje jako kwasy lub zasady zgodnie z teorią Brønsteda- Lowry’ego; wskazuje sprzężone pary kwas – zasada",
        "uzasadnia przyczynę kwasowego odczynu wodnych roztworów kwasów, zasadowego odczynu wodnych roztworów niektórych wodorotlenków (zasad) i amoniaku oraz odczynu niektórych wodnych roztworów soli zgodnie z teorią Brønsteda-Lowry’ego; pisze odpowiednie równania reakcji",
        "pisze równania reakcji: zobojętniania, wytrącania osadów i wybranych soli z wodą w formie jonowej pełnej i skróconej",
      ] },
    ] },
    { num: "VII", title: "Systematyka związków nieorganicznych", groups: [
      { label: null, points: [
        "na podstawie wzoru sumarycznego, opisu budowy lub właściwości fizykochemicznych klasyfikuje dany związek chemiczny do: tlenków, wodorków, wodorotlenków, kwasów, soli (w tym wodoro- i hydroksosoli, hydratów)",
        "na podstawie wzoru sumarycznego związku nieorganicznego pisze jego nazwę, na podstawie nazwy pisze jego wzór sumaryczny",
        "pisze równania reakcji otrzymywania tlenków pierwiastków o liczbach atomowych od 1 do 30 (synteza pierwiastków z tlenem, rozkład soli, np. CaCO3, i wodorotlenków, np. Cu(OH)2)",
        "opisuje typowe właściwości chemiczne tlenków pierwiastków o liczbach atomowych od 1 do 20 oraz Cr, Cu, Zn, Mn i Fe, w tym zachowanie wobec wody, kwasów i zasad; pisze odpowiednie równania reakcji w formie cząsteczkowej i jonowej",
        "klasyfikuje tlenki ze względu na ich charakter chemiczny (kwasowy, zasadowy, amfoteryczny i obojętny); projektuje i przeprowadza doświadczenie, którego przebieg pozwoli wykazać charakter chemiczny tlenku; wnioskuje o charakterze chemicznym tlenku na podstawie wyników doświadczenia",
        "klasyfikuje wodorki: LiH, CH4, NH3, H2O, HF, H2S, HCl, HBr, HI, ze względu na ich charakter chemiczny (kwasowy, zasadowy i obojętny); projektuje i przeprowadza doświadczenie, którego przebieg pozwoli wykazać charakter chemiczny wodorku; wnioskuje o charakterze chemicznym wodorku na podstawie wyników doświadczenia; pisze odpowiednie równania reakcji potwierdzające charakter chemiczny wodorków",
        "projektuje i przeprowadza doświadczenia pozwalające otrzymać różnymi metodami: wodorotlenki, kwasy i sole; pisze odpowiednie równania reakcji",
        "projektuje i przeprowadza doświadczenie, którego przebieg pozwoli wykazać charakter chemiczny wodorotlenku (zasadowy, amfoteryczny); wnioskuje o charakterze chemicznym wodorotlenku na podstawie wyników doświadczenia; pisze odpowiednie równania reakcji potwierdzające charakter chemiczny wodorotlenków (w tym równania reakcji otrzymywania hydroksokompleksów)",
        "opisuje typowe właściwości chemiczne kwasów, w tym zachowanie wobec metali, tlenków metali, wodorotlenków i soli kwasów o mniejszej mocy; projektuje i przeprowadza odpowiednie doświadczenia; pisze odpowiednie równania reakcji",
        "klasyfikuje poznane kwasy ze względu na ich skład (kwasy tlenowe i beztlenowe), moc i właściwości utleniające",
        "przewiduje przebieg reakcji soli z mocnymi kwasami (wypieranie kwasów słabszych, nietrwałych, lotnych) oraz soli z zasadami; pisze odpowiednie równania reakcji",
        "opisuje wpływ elektroujemności i stopnia utlenienia atomu centralnego na moc kwasów tlenowych",
      ] },
    ] },
    { num: "VIII", title: "Reakcje utleniania i redukcji", groups: [
      { label: null, points: [
        "stosuje pojęcia: stopień utlenienia, utleniacz, reduktor, utlenianie, redukcja",
        "wskazuje utleniacz, reduktor, proces utleniania i redukcji w podanej reakcji",
        "na podstawie konfiguracji elektronowej atomów przewiduje typowe stopnie utlenienia pierwiastków",
        "oblicza stopnie utlenienia pierwiastków w jonie i cząsteczce związku nieorganicznego i organicznego",
        "stosuje zasady bilansu elektronowo-jonowego – dobiera współczynniki stechiometryczne w schematach reakcji utleniania-redukcji (w formie cząsteczkowej i jonowej)",
        "przewiduje kierunek przebiegu reakcji utleniania-redukcji na podstawie wartości potencjałów standardowych półogniw; pisze odpowiednie równania reakcji",
      ] },
    ] },
    { num: "IX", title: "Elektrochemia. Ogniwa", groups: [
      { label: null, points: [
        "stosuje pojęcia: półogniwo, anoda, katoda, ogniwo galwaniczne, klucz elektrolityczny; potencjał standardowy półogniwa, szereg elektrochemiczny, SEM",
        "pisze oraz rysuje schemat ogniwa odwracalnego i nieodwracalnego",
        "pisze równania reakcji zachodzące na elektrodach (na katodzie i anodzie) ogniwa galwanicznego o danym schemacie; projektuje ogniwo, w którym zachodzi dana reakcja chemiczna; pisze schemat tego ogniwa",
        "oblicza SEM ogniwa galwanicznego na podstawie standardowych potencjałów półogniw, z których jest ono zbudowane",
        "wyszukuje, porządkuje, porównuje i prezentuje informacje: a) o przebiegu korozji elektrochemicznej stali i żeliwa oraz o sposobach ochrony metali przed korozją elektrochemiczną, b) na temat współczesnych źródeł prądu stałego",
      ] },
    ] },
    { num: "X", title: "Metale, niemetale i ich związki", groups: [
      { label: null, points: [
        "opisuje podobieństwa we właściwościach pierwiastków w grupach układu okresowego i zmienność właściwości w okresach",
        "opisuje podstawowe właściwości fizyczne metali i wyjaśnia je na podstawie znajomości natury wiązania metalicznego",
        "analizuje i porównuje właściwości fizyczne i chemiczne metali grup 1. i 2",
        "opisuje właściwości fizyczne i chemiczne glinu; wyjaśnia, na czym polega pasywacja glinu; tłumaczy znaczenie tego zjawiska w zastosowaniu glinu w technice",
        "pisze równania reakcji ilustrujące typowe właściwości chemiczne metali wobec: tlenu (dla Mg, Ca, Al, Zn), wody (dla Na, K, Mg, Ca), kwasów nieutleniających (dla Na, K, Ca, Mg, Al, Zn, Fe, Mn, Cr), przewiduje i opisuje przebieg reakcji rozcieńczonego i stężonego kwasu azotowego(V) oraz stężonego roztworu kwasu siarkowego(VI) z Al, Fe, Cu, Ag",
        "przewiduje produkty redukcji jonów manganianowych(VII) w zależności od środowiska, a także jonów dichromianowych(VI) w środowisku kwasowym; pisze odpowiednie równania reakcji",
        "projektuje i przeprowadza doświadczenia, w wyniku których można otrzymać wodór (reakcje aktywnych metali z wodą lub niektórych metali z niektórymi kwasami), pisze odpowiednie równania reakcji",
        "projektuje i obserwuje przebieg doświadczenia pozwalającego otrzymać w laboratorium: tlen (np. reakcja rozkładu H2O2 lub KMnO4), chlor (np. reakcja HCl z MnO2 lub z KMnO4); pisze odpowiednie równania reakcji",
        "pisze równania reakcji ilustrujące typowe właściwości chemiczne niemetali, w tym m.in. równania reakcji: wodoru z niemetalami (Cl2, Br2, O2, N2, S), chloru, bromu i siarki z metalami (Na, K, Mg, Ca, Fe, Cu); chloru z wodą",
        "analizuje i porównuje właściwości fizyczne i chemiczne fluorowców",
      ] },
    ] },
    { num: "XI", title: "Zastosowania wybranych związków nieorganicznych", groups: [
      { label: null, points: [
        "bada i opisuje właściwości tlenku krzemu(IV); wyszukuje, porządkuje, porównuje i prezentuje informacje o odmianach tlenku krzemu(IV) występujących w przyrodzie i ich zastosowaniach",
        "wyszukuje, porządkuje, porównuje i prezentuje informacje o procesie produkcji szkła; jego rodzajach, właściwościach i zastosowaniach",
        "wyszukuje, porządkuje, porównuje i prezentuje informacje o właściwościach i zastosowaniach skał wapiennych (wapień, marmur, kreda); projektuje i przeprowadza doświadczenie, którego celem będzie odróżnienie skał wapiennych od innych skał i minerałów; pisze odpowiednie równania reakcji",
        "opisuje mechanizm usuwania twardości przemijającej wody; pisze odpowiednie równania reakcji",
        "pisze wzory hydratów i soli bezwodnych (CaSO4, (CaSO4)2·H2O i CaSO4·2H2O); opisuje różnice we właściwościach hydratów i substancji bezwodnych; przewiduje zachowanie się hydratów podczas ogrzewania i weryfikuje swoje przewidywania doświadczalnie; wyjaśnia proces twardnienia zaprawy gipsowej; pisze odpowiednie równanie reakcji; wyszukuje, porządkuje, porównuje i prezentuje informacje o właściwościach i zastosowaniach skał gipsowych",
        "wyszukuje i prezentuje informacje na temat składu nawozów naturalnych i sztucznych oraz klasyfikuje je pod kątem zawartości pierwiastków",
      ] },
    ] },
    { num: "XII", title: "Wstęp do chemii organicznej", groups: [
      { label: null, points: [
        "na podstawie wzoru sumarycznego, półstrukturalnego (grupowego), opisu budowy lub właściwości fizykochemicznych klasyfikuje dany związek chemiczny do: węglowodorów (nasyconych, nienasyconych, cyklicznych, aromatycznych), związków jednofunkcyjnych (fluorowcopochodnych, alkoholi, fenoli, aldehydów, ketonów, kwasów karboksylowych, estrów, amin, amidów), związków wielofunkcyjnych (hydroksykwasów, aminokwasów, peptydów, białek, cukrów); na podstawie wzorów strukturalnych lub półstrukturalnych (grupowych) podaje nazwy systematyczne związków zawierających w szkielecie do 8 atomów węgla: węglowodorów, jednofunkcyjnych pochodnych węglowodorów (fluorowcopochodnych, alkoholi, fenoli, aldehydów, ketonów, kwasów karboksylowych, estrów); na podstawie nazw systematycznych rysuje ich wzory strukturalne i półstrukturalne (grupowe)",
        "stosuje pojęcia: homolog, szereg homologiczny, wzór ogólny, rzędowość w związkach organicznych, izomeria konstytucyjna (szkieletowa, położenia, grup funkcyjnych), stereoizomeria (izomeria geometryczna, izomeria optyczna); rozpoznaje i klasyfikuje izomery",
        "rysuje wzory strukturalne i półstrukturalne (grupowe) izomerów konstytucyjnych o podanym wzorze sumarycznym; wśród podanych wzorów węglowodorów i ich pochodnych wskazuje izomery konstytucyjne",
        "wyjaśnia zjawisko izomerii geometrycznej (cis-trans); uzasadnia warunki wystąpienia izomerii geometrycznej w cząsteczce związku o podanej nazwie lub o podanym wzorze strukturalnym (lub półstrukturalnym); rysuje wzory izomerów geometrycznych",
        "wyjaśnia zjawisko izomerii optycznej; wskazuje centrum stereogeniczne (asymetryczny atom węgla); rysuje wzory w projekcji Fischera izomerów optycznych: enancjomerów i diastereoizomerów; uzasadnia warunki wystąpienia izomerii optycznej w cząsteczce związku o podanej nazwie lub o podanym wzorze; ocenia, czy cząsteczka o podanym wzorze stereochemicznym jest chiralna",
        "analizuje zmiany właściwości fizycznych (np. temperatura topnienia, temperatura wrzenia, rozpuszczalność w wodzie) w szeregach homologicznych oraz analizuje i porównuje właściwości różnych izomerów konstytucyjnych; porównuje właściwości stereoizomerów (enancjomerów i diastereoizomerów)",
        "klasyfikuje reakcje związków organicznych ze względu na typ procesu (addycja, eliminacja, substytucja, polimeryzacja, kondensacja) i mechanizm reakcji (elektrofilowy, nukleofilowy, rodnikowy); wyjaśnia mechanizmy reakcji; pisze odpowiednie równania reakcji",
      ] },
    ] },
    { num: "XIII", title: "Węglowodory", groups: [
      { label: null, points: [
        "ustala rzędowość atomów węgla w cząsteczce węglowodoru",
        "opisuje właściwości chemiczne alkanów na przykładzie reakcji: spalania, substytucji atomu (lub atomów) wodoru przez atom (lub atomy) chloru albo bromu przy udziale światła; pisze odpowiednie równania reakcji",
        "opisuje właściwości chemiczne alkenów na przykładzie reakcji: spalania, addycji: H2, Cl2 i Br2, HCl i HBr, H2O, polimeryzacji; przewiduje produkty reakcji przyłączenia cząsteczek niesymetrycznych do niesymetrycznych alkenów na podstawie reguły Markownikowa (produkty główne i uboczne); opisuje zachowanie alkenów wobec wodnego roztworu manganianu(VII) potasu; pisze odpowiednie równania reakcji",
        "planuje ciąg przemian pozwalających otrzymać np. alken z alkanu (z udziałem fluorowcopochodnych węglowodorów); pisze odpowiednie równania reakcji",
        "opisuje właściwości chemiczne alkinów na przykładzie reakcji spalania, addycji: H2, Cl2 i Br2, HCl, i HBr, H2O; pisze odpowiednie równania reakcji",
        "ustala wzór monomeru, z którego został otrzymany polimer o podanej strukturze; rysuje wzór polimeru powstającego z monomeru o podanym wzorze lub nazwie; pisze odpowiednie równania reakcji",
        "wyszukuje, porządkuje i prezentuje informacje o tworzywach; wskazuje na zagrożenia związane z gazami powstającymi w wyniku ich spalania",
        "opisuje budowę cząsteczki benzenu, z uwzględnieniem delokalizacji elektronów; wyjaśnia, dlaczego benzen, w przeciwieństwie do alkenów i alkinów, nie odbarwia wody bromowej ani wodnego roztworu manganianu(VII) potasu",
        "opisuje właściwości chemiczne benzenu i toluenu (metylobenzenu) (węglowodorów aromatycznych) na przykładzie reakcji: spalania, z Cl2 lub Br2 wobec katalizatora albo w obecności światła, nitrowania, katalitycznego uwodornienia; pisze równania reakcji chlorowcowania i nitrowania pochodnych benzenu (odpowiednie równania reakcji dla benzenu i metylobenzenu (toluenu) oraz ich pochodnych), uwzględniając wpływ kierujący podstawników (atom chlorowca, grupa alkilowa, grupa nitrowa, grupa hydroksylowa, grupa karboksylowa)",
        "projektuje doświadczenia pozwalające na wskazanie różnic we właściwościach chemicznych węglowodorów nasyconych, nienasyconych i aromatycznych; na podstawie wyników przeprowadzonych doświadczeń wnioskuje o rodzaju węglowodoru; pisze odpowiednie równania reakcji",
        "wyszukuje, porządkuje, porównuje i prezentuje informacje na temat destylacji ropy naftowej i pirolizy węgla kamiennego; wymienia nazwy produktów tych procesów i ich zastosowania",
        "wyjaśnia pojęcie liczby oktanowej (LO) i podaje sposoby zwiększania LO benzyny; tłumaczy, na czym polega kraking oraz reforming",
        "podaje nazwy systematyczne węglowodorów (alkanu, alkenu i alkinu –do 10 atomów węgla w cząsteczce – oraz węglowodorów cyklicznych i aromatycznych) na podstawie wzorów strukturalnych, półstrukturalnych (grupowych) lub uproszczonych; rysuje wzory węglowodorów na podstawie ich nazw; podaje nazwy systematyczne fluorowcopochodnych węglowodorów na podstawie wzorów strukturalnych lub półstrukturalnych (grupowych); rysuje ich wzory strukturalne i półstrukturalne (grupowe) na podstawie nazw systematycznych; 13 (zawartość punktu przeniesiona do wstępu do chemii organicznej z jednoczesnym skróceniem opisywanych cząsteczek do 8 atomów węgla)",
      ] },
    ] },
    { num: "XIV", title: "Hydroksylowe pochodne węglowodorów − alkohole i fenole", groups: [
      { label: null, points: [
        "porównuje budowę cząsteczek alkoholi i fenoli; wskazuje wzory alkoholi pierwszo-, drugo-, i trzeciorzędowych",
        "opisuje właściwości chemiczne alkoholi na przykładzie reakcji: spalania, z HCl i Hbr, zachowania wobec sodu, utlenienia do związków karbonylowych, eliminacji wody, reakcji z nieorganicznymi kwasami tlenowymi i kwasami karboksylowymi; pisze odpowiednie równania reakcji",
        "porównuje właściwości fizyczne i chemiczne alkoholi mono- i polihydroksylowych (etanolu (alkoholu etylowego), etano-1,2-diolu (glikolu etylenowego), propano-1,2-diolu (glikolu propylenowego) i propano-1,2,3- triolu (glicerolu)); projektuje i przeprowadza doświadczenie, którego przebieg pozwoli odróżnić alkohol monohydroksylowy od alkoholu polihydroksylowego; na podstawie obserwacji wyników doświadczenia klasyfikuje alkohol do mono- lub polihydroksylowych",
        "opisuje zachowanie: alkoholi pierwszo-, drugo- i trzeciorzędowych wobec utleniaczy (np. CuO lub K2Cr2O7/H2SO4); projektuje i przeprowadza doświadczenie, którego przebieg pozwoli odróżnić alkohol trzeciorzędowy od alkoholu pierwszo- i drugorzędowego; pisze odpowiednie równania reakcji",
        "pisze równanie reakcji manganianu(VII) potasu (w środowisku kwasowym) z alkoholem (np. z etanolem, etano-1,2-diolem)",
        "opisuje właściwości chemiczne fenoli na podstawie reakcji z: sodem, wodorotlenkiem sodu, bromem, kwasem azotowym(V); pisze odpowiednie równania reakcji dla fenolu (benzenolu, hydroksybenzenu) i jego pochodnych; na podstawie wyników doświadczenia (reakcji kwasowo-zasadowych lub reakcji z FeCl3) klasyfikuje substancję do alkoholi lub fenoli",
        "na podstawie obserwacji doświadczeń formułuje wniosek dotyczący kwasowego charakteru fenolu; projektuje i przeprowadza doświadczenie, które umożliwi porównanie mocy kwasów, np. fenolu i kwasu węglowego; pisze odpowiednie równania reakcji",
        "planuje ciągi przemian pozwalających otrzymać alkohol lub fenol z odpowiedniego węglowodoru; pisze odpowiednie równania reakcji",
        "wyszukuje, porządkuje i prezentuje informacje o metodach otrzymywania, właściwościach fizycznych i chemicznych oraz zastosowaniach alkoholi i fenoli",
        "na podstawie wzoru strukturalnego, półstrukturalnego (grupowego) lub uproszczonego podaje nazwy systematyczne alkoholi i fenoli; na podstawie nazwy systematycznej lub zwyczajowej rysuje ich wzory strukturalne, półstrukturalne (grupowe) lub uproszczone; (zawartość punktu przeniesiona do wstępu do chemii organicznej)",
      ] },
    ] },
    { num: "XV", title: "Związki karbonylowe − aldehydy i ketony", groups: [
      { label: null, points: [
        "opisuje podobieństwa i różnice w budowie cząsteczek aldehydów i ketonów (położenie (obecność) grupy karbonylowej)",
        "projektuje i przeprowadza doświadczenie, którego przebieg pozwoli odróżnić aldehyd od ketonu; na podstawie wyników doświadczenia klasyfikuje substancję do aldehydów lub ketonów; pisze odpowiednie równania reakcji aldehydu z odczynnikiem Tollensa i odczynnikiem Trommera",
        "wyszukuje, porządkuje i prezentuje informacje o metodach otrzymywania, właściwościach i zastosowaniach aldehydów i ketonów",
        "na podstawie wzoru strukturalnego lub półstrukturalnego (grupowego) podaje nazwy systematyczne aldehydów i ketonów; na podstawie nazwy systematycznej rysuje wzory strukturalne lub półstrukturalne (grupowe); (zawartość punktu przeniesiona do wstępu do chemii organicznej)",
      ] },
    ] },
    { num: "XVI", title: "Kwasy karboksylowe", groups: [
      { label: null, points: [
        "wskazuje grupę karboksylową i resztę kwasową we wzorach kwasów karboksylowych (alifatycznych i aromatycznych); na podstawie wzoru strukturalnego lub półstrukturalnego (grupowego) podaje nazwy systematyczne (lub zwyczajowe) kwasów karboksylowych; na podstawie nazwy systematycznej (lub zwyczajowej) rysuje wzory strukturalne lub półstrukturalne (grupowe) (wykreślona zawartość punktu przeniesiona do wstępu do chemii organicznej)",
        "pisze równania reakcji otrzymywania kwasów karboksylowych (np. z alkoholi lub z aldehydów)",
        "pisze równania dysocjacji elektrolitycznej rozpuszczalnych w wodzie kwasów karboksylowych i nazywa powstające w tych reakcjach jony",
        "opisuje właściwości chemiczne kwasów karboksylowych na podstawie reakcji tworzenia: soli, estrów, amidów; pisze odpowiednie równania reakcji; projektuje i przeprowadza doświadczenia pozwalające otrzymywać sole kwasów karboksylowych (w reakcjach kwasów z: metalami, tlenkami metali, wodorotlenkami metali i solami kwasów o mniejszej mocy)",
        "opisuje czynniki wpływające na moc kwasów karboksylowych (długość łańcucha węglowego, obecność polarnych podstawników)",
        "na podstawie wyników doświadczenia porównuje moc kwasów",
        "wyszukuje, porządkuje i prezentuje informacje o zastosowaniu kwasów karboksylowych",
        "wyszukuje, porządkuje i prezentuje informacje o budowie, występowaniu i zastosowaniach hydroksykwasów oraz możliwości tworzenia przez nie estrów międzycząsteczkowych (laktydy, poliestry) i wewnątrzcząsteczkowych (laktony)",
        "uzasadnia przyczynę redukujących właściwościach kwasu metanowego (mrówkowego); projektuje doświadczenie, którego wynik wykaże właściwości redukujące kwasu metanowego (mrówkowego) (reakcja HCOOH z MnO4−); pisze odpowiednie równania reakcji",
      ] },
    ] },
    { num: "XVII", title: "Estry i tłuszcze", groups: [
      { label: null, points: [
        "opisuje strukturę cząsteczek estrów i wiązania estrowego",
        "projektuje i przeprowadza reakcje estryfikacji; pisze równania reakcji alkoholi z kwasami nieorganicznymi i karboksylowymi; wskazuje na funkcję stężonego H2SO4",
        "wskazuje wpływ różnych czynników na położenie stanu równowagi reakcji estryfikacji lub hydrolizy estru",
        "wyjaśnia i porównuje przebieg hydrolizy estrów (np. octanu etylu, tłuszczów) w środowisku kwasowym (reakcja z wodą w obecności kwasu siarkowego(VI)) oraz w środowisku zasadowym (reakcja z wodorotlenkiem sodu); pisze odpowiednie równania reakcji",
        "opisuje budowę tłuszczów stałych i ciekłych (jako estrów glicerolu i długołańcuchowych kwasów tłuszczowych)",
        "wyszukuje, porządkuje i prezentuje informacje o procesie usuwania brudu (wyjaśnia, na czym polega proces usuwania brudu; bada wpływ twardości wody na powstawanie związków trudno rozpuszczalnych)",
        "zaznacza fragmenty hydrofobowe i hydrofilowe we wzorach cząsteczek substancji powierzchniowo czynnych",
        "planuje ciągi przemian chemicznych wiążące ze sobą właściwości poznanych węglowodorów i ich pochodnych; pisze odpowiednie równania reakcji",
        "wyszukuje, porządkuje i prezentuje informacje o właściwościach fizycznych, chemicznych i zastosowaniach estrów i tłuszczów",
        "tworzy nazwy (systematyczne lub zwyczajowe) estrów kwasów karboksylowych i tlenowych kwasów nieorganicznych; rysuje wzory strukturalne i półstrukturalne (grupowe) estrów na podstawie ich nazwy; (zawartość punktu przeniesiona do wstępu do chemii organicznej)",
      ] },
    ] },
    { num: "XVIII", title: "Związki organiczne zawierające azot", groups: [
      { label: null, points: [
        "opisuje budowę amin; wskazuje wzory amin pierwszo-, drugo- i trzeciorzędowych",
        "porównuje budowę amoniaku i amin; rysuje wzory elektronowe cząsteczek amoniaku i aminy (np. metyloaminy)",
        "wskazuje podobieństwa i różnice w budowie amin alifatycznych (np. metyloaminy) i amin aromatycznych (fenyloaminy (aniliny))",
        "porównuje i wyjaśnia przyczynę zasadowych właściwości amoniaku i amin; pisze odpowiednie równania reakcji",
        "opisuje właściwości chemiczne amin na podstawie reakcji: z wodą, z kwasami nieorganicznymi i z kwasami karboksylowymi; pisze odpowiednie równania reakcji",
        "pisze wzór ogólny α-aminokwasów w postaci RCH(NH2)COOH; wyjaśnia, co oznacza, że aminokwasy białkowe są α-aminokwasami i należą do szeregu konfiguracyjnego L",
        "opisuje właściwości kwasowo-zasadowe aminokwasów oraz mechanizm powstawania jonów obojnaczych",
        "pisze równania reakcji kondensacji cząsteczek aminokwasów (o podanych wzorach) prowadzących do powstania di- i tripeptydów i wskazuje wiązania peptydowe w otrzymanym produkcie",
        "tworzy wzory dipeptydów i tripeptydów, powstających z podanych aminokwasów; rozpoznaje reszty aminokwasów białkowych w cząsteczkach peptydów",
        "opisuje przebieg hydrolizy peptydów, rysuje wzory półstrukturalne (grupowe) aminokwasów powstających w procesie hydrolizy peptydu o danej strukturze",
        "projektuje i przeprowadza doświadczenie, którego wynik dowiedzie obecności wiązań peptydowych w analizowanym związku (reakcja biuretowa)",
        "pisze równania reakcji otrzymywania amin alifatycznych (np. w procesie alkilowania amoniaku) i amin aromatycznych (np. otrzymywanie aniliny w wyniku reakcji redukcji nitrobenzenu)",
        "pisze równanie reakcji fenyloaminy (aniliny) z wodą bromową",
        "pisze równania reakcji hydrolizy amidów (np. acetamidu) w środowisku kwasowym i zasadowym",
        "pisze równanie reakcji kondensacji dwóch cząsteczek mocznika; wykazuje, że produktem kondensacji mocznika jest związek zawierający w cząsteczce wiązanie amidowe (peptydowe)",
      ] },
    ] },
    { num: "XIX", title: "Białka", groups: [
      { label: null, points: [
        "wyszukuje, porządkuje, porównuje i prezentuje informacje o budowie, właściwościach fizycznych, znaczeniu i zastosowaniu białek",
        "obserwuje proces denaturacji białek wywołanej oddziaływaniem na nie soli metali ciężkich i wysokiej temperatury; wymienia czynniki wywołujące wysalanie białek i wyjaśnia ten proces",
        "wyszukuje, porządkuje, porównuje i prezentuje informacje o budowie drugorzędowej (α- i β-) oraz trzeciorzędowej (wiązania jonowe, mostki disiarczkowe, wiązania wodorowe i oddziaływania van der Waalsa) białek",
        "projektuje i przeprowadza doświadczenie pozwalające na identyfikację białek (reakcja biuretowa i reakcja ksantoproteinowa)",
      ] },
    ] },
    { num: "XX", title: "Cukry", groups: [
      { label: null, points: [
        "dokonuje podziału cukrów na proste i złożone, klasyfikuje cukry proste ze względu na grupę funkcyjną i liczbę atomów węgla w cząsteczce; wyjaśnia, co oznacza, że naturalne monosacharydy należą do szeregu konfiguracyjnego D",
        "wyszukuje, porządkuje i prezentuje informacje o pochodzeniu cukrów prostych, zawartych np. w owocach (fotosynteza)",
        "zapisuje wzory łańcuchowe w projekcji Fischera glukozy i fruktozy; wykazuje, że cukry proste należą do polihydroksyaldehydów lub polihydroksyketonów; rysuje wzory taflowe (Hawortha) anomerów α i β glukozy i fruktozy; na podstawie wzoru łańcuchowego monosacharydu rysuje jego wzory taflowe; na podstawie wzoru taflowego rysuje wzór w projekcji Fischera; rozpoznaje reszty glukozy i fruktozy w disacharydach i polisacharydach o podanych wzorach",
        "projektuje i przeprowadza doświadczenie, którego wynik potwierdzi właściwości redukujące np. glukozy; projektuje i przeprowadza doświadczenie, którego wynik potwierdzi obecność grup hydroksylowych w cząsteczce monosacharydu, np. glukozy",
        "projektuje i przeprowadza doświadczenie pozwalające na odróżnienie glukozy i fruktozy",
        "wskazuje wiązanie O-glikozydowe w cząsteczkach cukrów o podanych wzorach (np. sacharozy, maltozy, celobiozy)",
        "wyjaśnia, dlaczego maltoza ma właściwości redukujące, a sacharoza nie wykazuje właściwości redukujących",
        "obserwuje różnice we właściwościach skrobi i celulozy",
        "planuje ciąg przemian pozwalających przekształcić cukry w inne związki organiczne (np. glukozę w alkohol etylowy, a następnie w octan etylu); pisze odpowiednie równania reakcji",
      ] },
    ] },
    { num: "XXI", title: "Chemia wokół nas", groups: [
      { label: null, points: [
        "o właściwościach leczniczych i toksycznych substancji chemicznych (dawka, rozpuszczalność w wodzie, sposób przenikania do organizmu), np. leków, nikotyny, etanolu",
        "na temat działania składników popularnych leków (np. węgla aktywowanego, kwasu acetylosalicylowego, środków neutralizujących nadmiar kwasu w żołądku)",
        "na temat składników zawartych w kawie, herbacie, mleku, wodzie mineralnej, napojach typu cola w aspekcie ich działania na organizm ludzki",
        "o procesach zachodzących podczas wyrabiania ciasta i pieczenia chleba, produkcji wina, otrzymywania kwaśnego mleka, jogurtów, serów",
        "o chemicznym składzie środków do mycia szkła, przetykania rur, czyszczenia metali i biżuterii w aspekcie zastosowań tych produktów; stosuje te środki, z uwzględnieniem zasad bezpieczeństwa",
      ] },
    ] },
    { num: "XXII", title: "Elementy ochrony środowiska", groups: [
      { label: null, points: [
        "tłumaczy, na czym polegają sorpcyjne właściwości gleby w uprawie roślin i ochronie środowiska; planuje i przeprowadza badanie kwasowości gleby oraz badanie właściwości sorpcyjnych gleby",
        "wyszukuje, porządkuje i prezentuje informacje o rodzajach zanieczyszczeń powietrza, wody i gleby (np. metale ciężkie, węglowodory, produkty spalania paliw, freony, pyły, azotany(V), fosforany(V) (ortofosforany(V)), ich źródła oraz wpływ na stan środowiska naturalnego, w tym klimatu",
        "proponuje sposoby ochrony środowiska naturalnego przed zanieczyszczeniem i degradacją zgodnie z zasadami zrównoważonego rozwoju",
        "wskazuje potrzebę rozwoju gałęzi przemysłu chemicznego (leki, źródła energii, materiały); wskazuje problemy i zagrożenia wynikające z niewłaściwego planowania i prowadzenia procesów chemicznych; uzasadnia konieczność projektowania i wdrażania procesów chemicznych umożliwiających ograniczenie lub wyeliminowanie używania albo wytwarzania niebezpiecznych substancji; wyjaśnia zasady tzw. zielonej chemii",
      ] },
    ] },
  ],
};
