// Pytania jawne na maturę ustną z języka polskiego — 75 pytań przypisanych do lektur.
// Klucz = dokładny tytuł lektury z PLANER_LEKTURY (js/data-listy.js).
// temat  — zagadnienie, zrodlo — polecenie „Omów zagadnienie na podstawie…".
window.PLANER_PYTANIA = {
  "Biblia — Ks. Rodzaju, Hioba, Koheleta, Psalmów, Apokalipsa św. Jana (fragmenty)": [
    { nr: 1, temat: "Motyw cierpienia niezawinionego.",
      zrodlo: "Omów zagadnienie na podstawie znanych Ci fragmentów „Księgi Hioba”. W swojej odpowiedzi uwzględnij również wybrany kontekst." },
    { nr: 2, temat: "Człowiek wobec niestałości świata.",
      zrodlo: "Omów zagadnienie na podstawie znanych Ci fragmentów „Księgi Koheleta”. W swojej odpowiedzi uwzględnij również wybrany kontekst." },
    { nr: 3, temat: "Wizja końca świata.",
      zrodlo: "Omów zagadnienie na podstawie znanych Ci fragmentów „Apokalipsy św. Jana”. W swojej odpowiedzi uwzględnij również wybrany kontekst." },
  ],
  "Jan Parandowski, Mitologia, cz. I Grecja": [
    { nr: 4, temat: "Poświęcenie się w imię wyższych wartości.",
      zrodlo: "Omów zagadnienie na podstawie „Mitologii” (cz. I „Grecja”) Jana Parandowskiego. W swojej odpowiedzi uwzględnij również wybrany kontekst." },
    { nr: 5, temat: "Problematyka winy i kary.",
      zrodlo: "Omów zagadnienie na podstawie „Mitologii” (cz. I „Grecja”) Jana Parandowskiego. W swojej odpowiedzi uwzględnij również wybrany kontekst." },
    { nr: 6, temat: "Miłość silniejsza niż śmierć.",
      zrodlo: "Omów zagadnienie na podstawie „Mitologii” (cz. I „Grecja”) Jana Parandowskiego. W swojej odpowiedzi uwzględnij również wybrany kontekst." },
  ],
  "Homer, Iliada (fragmenty)": [
    { nr: 7, temat: "Heroizm jako postawa człowieka w zmaganiu się z losem.",
      zrodlo: "Omów zagadnienie na podstawie znanych Ci fragmentów „Iliady” Homera. W swojej odpowiedzi uwzględnij również wybrany kontekst." },
  ],
  "Sofokles, Antygona": [
    { nr: 8, temat: "Prawa boskie a prawa ludzkie.",
      zrodlo: "Omów zagadnienie na podstawie „Antygony” Sofoklesa. W swojej odpowiedzi uwzględnij również wybrany kontekst." },
    { nr: 9, temat: "Człowiek wobec przeznaczenia.",
      zrodlo: "Omów zagadnienie na podstawie „Antygony” Sofoklesa. W swojej odpowiedzi uwzględnij również wybrany kontekst." },
  ],
  "Lament świętokrzyski (fragmenty)": [
    { nr: 10, temat: "Motyw cierpiącej matki.",
      zrodlo: "Omów zagadnienie na podstawie znanych Ci fragmentów „Lamentu świętokrzyskiego”. W swojej odpowiedzi uwzględnij również wybrany kontekst." },
  ],
  "Rozmowa Mistrza Polikarpa ze Śmiercią (fragmenty)": [
    { nr: 11, temat: "Motyw tańca śmierci.",
      zrodlo: "Omów zagadnienie na podstawie znanych Ci fragmentów „Rozmowy Mistrza Polikarpa ze Śmiercią”. W swojej odpowiedzi uwzględnij również wybrany kontekst." },
  ],
  "Pieśń o Rolandzie (fragmenty)": [
    { nr: 12, temat: "Średniowieczny wzorzec rycerza.",
      zrodlo: "Omów zagadnienie na podstawie znanych Ci fragmentów „Pieśni o Rolandzie”. W swojej odpowiedzi uwzględnij również wybrany kontekst." },
  ],
  "William Szekspir, Makbet": [
    { nr: 13, temat: "Moralna odpowiedzialność za czyny.",
      zrodlo: "Omów zagadnienie na podstawie „Makbeta” Williama Szekspira. W swojej odpowiedzi uwzględnij również wybrany kontekst." },
    { nr: 14, temat: "Czy człowiek decyduje o własnym losie?",
      zrodlo: "Omów zagadnienie na podstawie „Makbeta” Williama Szekspira. W swojej odpowiedzi uwzględnij również wybrany kontekst." },
    { nr: 15, temat: "Jaki wpływ na człowieka ma sprawowanie przez niego władzy?",
      zrodlo: "Omów zagadnienie na podstawie „Makbeta” Williama Szekspira. W swojej odpowiedzi uwzględnij również wybrany kontekst." },
  ],
  "Molier, Skąpiec": [
    { nr: 16, temat: "Czy dobra materialne czynią człowieka szczęśliwym?",
      zrodlo: "Omów zagadnienie na podstawie „Skąpca” Moliera. W swojej odpowiedzi uwzględnij również wybrany kontekst." },
    { nr: 17, temat: "Przyczyny nieporozumień między rodzicami a dziećmi.",
      zrodlo: "Omów zagadnienie na podstawie „Skąpca” Moliera. W swojej odpowiedzi uwzględnij również wybrany kontekst." },
  ],
  "Ignacy Krasicki, wybrana satyra": [
    { nr: 18, temat: "Wady ludzkie w krzywym zwierciadle satyry.",
      zrodlo: "Omów zagadnienie na podstawie znanej Ci satyry Ignacego Krasickiego. W swojej odpowiedzi uwzględnij również wybrany kontekst." },
  ],
  "Adam Mickiewicz, wybrane ballady, w tym Romantyczność": [
    { nr: 19, temat: "Świat ducha a świat rozumu.",
      zrodlo: "Omów zagadnienie na podstawie „Romantyczności” Adama Mickiewicza. W swojej odpowiedzi uwzględnij również wybrany kontekst." },
    { nr: 20, temat: "Na czym polega ludowa sprawiedliwość?",
      zrodlo: "Omów zagadnienie na podstawie znanych Ci ballad Adama Mickiewicza. W swojej odpowiedzi uwzględnij również wybrany kontekst." },
  ],
  "Adam Mickiewicz, Dziady cz. III": [
    { nr: 21, temat: "Losy młodzieży polskiej pod zaborami.",
      zrodlo: "Omów zagadnienie na podstawie „Dziadów” części III Adama Mickiewicza. W swojej odpowiedzi uwzględnij również wybrany kontekst." },
    { nr: 22, temat: "Mesjanizm jako romantyczna idea poświęcenia.",
      zrodlo: "Omów zagadnienie na podstawie „Dziadów” części III Adama Mickiewicza. W swojej odpowiedzi uwzględnij również wybrany kontekst." },
    { nr: 23, temat: "Postawy społeczeństwa polskiego wobec zaborcy.",
      zrodlo: "Omów zagadnienie na podstawie „Dziadów” części III Adama Mickiewicza. W swojej odpowiedzi uwzględnij również wybrany kontekst." },
    { nr: 24, temat: "Różne postawy człowieka wobec Boga.",
      zrodlo: "Omów zagadnienie na podstawie „Dziadów” części III Adama Mickiewicza. W swojej odpowiedzi uwzględnij również wybrany kontekst." },
    { nr: 25, temat: "Jakie prawdy o człowieku ujawniają jego sny albo widzenia?",
      zrodlo: "Omów zagadnienie na podstawie „Dziadów” części III Adama Mickiewicza. W swojej odpowiedzi uwzględnij również wybrany kontekst." },
    { nr: 26, temat: "W jakim celu twórca nawiązuje do motywów biblijnych?",
      zrodlo: "Omów zagadnienie na podstawie „Dziadów” części III Adama Mickiewicza. W swojej odpowiedzi uwzględnij również wybrany kontekst." },
    { nr: 27, temat: "Walka dobra ze złem o duszę ludzką.",
      zrodlo: "Omów zagadnienie na podstawie „Dziadów” części III Adama Mickiewicza. W swojej odpowiedzi uwzględnij również wybrany kontekst." },
    { nr: 28, temat: "Czym dla człowieka może być wolność?",
      zrodlo: "Omów zagadnienie na podstawie „Dziadów” części III Adama Mickiewicza. W swojej odpowiedzi uwzględnij również wybrany kontekst." },
    { nr: 29, temat: "Motyw samotności.",
      zrodlo: "Omów zagadnienie na podstawie „Dziadów” części III Adama Mickiewicza. W swojej odpowiedzi uwzględnij również wybrany kontekst." },
  ],
  "Bolesław Prus, Lalka": [
    { nr: 30, temat: "Miłość – siła destrukcyjna czy motywująca do działania?",
      zrodlo: "Omów zagadnienie na podstawie „Lalki” Bolesława Prusa. W swojej odpowiedzi uwzględnij również wybrany kontekst." },
    { nr: 31, temat: "Praca jako pasja człowieka.",
      zrodlo: "Omów zagadnienie na podstawie „Lalki” Bolesława Prusa. W swojej odpowiedzi uwzględnij również wybrany kontekst." },
    { nr: 32, temat: "Jaką rolę w relacjach międzyludzkich odgrywają majątek i pochodzenie?",
      zrodlo: "Omów zagadnienie na podstawie „Lalki” Bolesława Prusa. W swojej odpowiedzi uwzględnij również wybrany kontekst." },
    { nr: 33, temat: "Konfrontacja marzeń z rzeczywistością.",
      zrodlo: "Omów zagadnienie na podstawie „Lalki” Bolesława Prusa. W swojej odpowiedzi uwzględnij również wybrany kontekst." },
    { nr: 34, temat: "Miasto – przestrzeń przyjazna czy wroga człowiekowi?",
      zrodlo: "Omów zagadnienie na podstawie „Lalki” Bolesława Prusa. W swojej odpowiedzi uwzględnij również wybrany kontekst." },
    { nr: 35, temat: "Czym dla człowieka mogą być wspomnienia?",
      zrodlo: "Omów zagadnienie na podstawie „Lalki” Bolesława Prusa. W swojej odpowiedzi uwzględnij również wybrany kontekst." },
  ],
  "Henryk Sienkiewicz, Potop (fragmenty)": [
    { nr: 36, temat: "Postawy odwagi i tchórzostwa.",
      zrodlo: "Omów zagadnienie na podstawie znanych Ci fragmentów „Potopu” Henryka Sienkiewicza. W swojej odpowiedzi uwzględnij również wybrany kontekst." },
  ],
  "Fiodor Dostojewski, Zbrodnia i kara": [
    { nr: 37, temat: "Walka człowieka ze swoimi słabościami.",
      zrodlo: "Omów zagadnienie na podstawie „Zbrodni i kary” Fiodora Dostojewskiego. W swojej odpowiedzi uwzględnij również wybrany kontekst." },
    { nr: 38, temat: "Motyw winy i kary.",
      zrodlo: "Omów zagadnienie na podstawie „Zbrodni i kary” Fiodora Dostojewskiego. W swojej odpowiedzi uwzględnij również wybrany kontekst." },
    { nr: 39, temat: "Ile człowiek jest gotów poświęcić dla innych?",
      zrodlo: "Omów zagadnienie na podstawie „Zbrodni i kary” Fiodora Dostojewskiego. W swojej odpowiedzi uwzględnij również wybrany kontekst." },
    { nr: 40, temat: "Co może determinować ludzkie postępowanie?",
      zrodlo: "Omów zagadnienie na podstawie „Zbrodni i kary” Fiodora Dostojewskiego. W swojej odpowiedzi uwzględnij również wybrany kontekst." },
    { nr: 41, temat: "Motyw przemiany bohatera.",
      zrodlo: "Omów zagadnienie na podstawie „Zbrodni i kary” Fiodora Dostojewskiego. W swojej odpowiedzi uwzględnij również wybrany kontekst." },
  ],
  "Stanisław Wyspiański, Wesele": [
    { nr: 42, temat: "Co utrudnia porozumienie między przedstawicielami różnych grup społecznych?",
      zrodlo: "Omów zagadnienie na podstawie „Wesela” Stanisława Wyspiańskiego. W swojej odpowiedzi uwzględnij również wybrany kontekst." },
    { nr: 43, temat: "Rola chłopów i inteligencji w sprawie niepodległościowej.",
      zrodlo: "Omów zagadnienie na podstawie „Wesela” Stanisława Wyspiańskiego. W swojej odpowiedzi uwzględnij również wybrany kontekst." },
    { nr: 44, temat: "Sen o Polsce czy sąd nad Polską?",
      zrodlo: "Omów zagadnienie na podstawie „Wesela” Stanisława Wyspiańskiego. W swojej odpowiedzi uwzględnij również wybrany kontekst." },
    { nr: 45, temat: "Symboliczne znaczenie widm i zjaw.",
      zrodlo: "Omów zagadnienie na podstawie „Wesela” Stanisława Wyspiańskiego. W swojej odpowiedzi uwzględnij również wybrany kontekst." },
    { nr: 46, temat: "Motyw tańca.",
      zrodlo: "Omów zagadnienie na podstawie „Wesela” Stanisława Wyspiańskiego. W swojej odpowiedzi uwzględnij również wybrany kontekst." },
  ],
  "Władysław Stanisław Reymont, Chłopi (fragmenty)": [
    { nr: 47, temat: "Obyczaj i tradycja w życiu społeczeństwa.",
      zrodlo: "Omów zagadnienie na podstawie znanych Ci fragmentów „Chłopów” Władysława Stanisława Reymonta. W swojej odpowiedzi uwzględnij również wybrany kontekst." },
  ],
  "Stefan Żeromski, Przedwiośnie": [
    { nr: 48, temat: "Jakie znaczenie ma tytuł dla odczytania sensu utworu?",
      zrodlo: "Omów zagadnienie na podstawie „Przedwiośnia” Stefana Żeromskiego. W swojej odpowiedzi uwzględnij również wybrany kontekst." },
    { nr: 49, temat: "Wojna i rewolucja jako źródła doświadczeń człowieka.",
      zrodlo: "Omów zagadnienie na podstawie „Przedwiośnia” Stefana Żeromskiego. W swojej odpowiedzi uwzględnij również wybrany kontekst." },
    { nr: 50, temat: "Różne wizje odbudowy Polski po odzyskaniu niepodległości.",
      zrodlo: "Omów zagadnienie na podstawie „Przedwiośnia” Stefana Żeromskiego. W swojej odpowiedzi uwzględnij również wybrany kontekst." },
    { nr: 51, temat: "Młodość jako czas kształtowania własnej tożsamości.",
      zrodlo: "Omów zagadnienie na podstawie „Przedwiośnia” Stefana Żeromskiego. W swojej odpowiedzi uwzględnij również wybrany kontekst." },
    { nr: 52, temat: "Rola autorytetu w życiu człowieka.",
      zrodlo: "Omów zagadnienie na podstawie „Przedwiośnia” Stefana Żeromskiego. W swojej odpowiedzi uwzględnij również wybrany kontekst." },
    { nr: 53, temat: "Utopijny i realny obraz rzeczywistości.",
      zrodlo: "Omów zagadnienie na podstawie „Przedwiośnia” Stefana Żeromskiego. W swojej odpowiedzi uwzględnij również wybrany kontekst." },
  ],
  "Witold Gombrowicz, Ferdydurke (fragmenty)": [
    { nr: 54, temat: "Groteskowy obraz świata.",
      zrodlo: "Omów zagadnienie na podstawie znanych Ci fragmentów „Ferdydurke” Witolda Gombrowicza. W swojej odpowiedzi uwzględnij również wybrany kontekst." },
    { nr: 55, temat: "Człowiek wobec presji otoczenia.",
      zrodlo: "Omów zagadnienie na podstawie znanych Ci fragmentów „Ferdydurke” Witolda Gombrowicza. W swojej odpowiedzi uwzględnij również wybrany kontekst." },
  ],
  "Tadeusz Borowski, Proszę państwa do gazu": [
    { nr: 56, temat: "„Człowiek zlagrowany” jako ofiara zbrodniczego systemu.",
      zrodlo: "Omów zagadnienie na podstawie utworu „Proszę państwa do gazu” Tadeusza Borowskiego. W swojej odpowiedzi uwzględnij również wybrany kontekst." },
  ],
  "Gustaw Herling-Grudziński, Inny świat (fragmenty)": [
    { nr: 57, temat: "Jakie znaczenie ma tytuł dla odczytania sensu utworu?",
      zrodlo: "Omów zagadnienie na podstawie znanych Ci fragmentów „Innego świata” Gustawa Herlinga-Grudzińskiego. W swojej odpowiedzi uwzględnij również wybrany kontekst." },
    { nr: 58, temat: "Konsekwencje zniewolenia człowieka.",
      zrodlo: "Omów zagadnienie na podstawie znanych Ci fragmentów „Innego świata” Gustawa Herlinga-Grudzińskiego. W swojej odpowiedzi uwzględnij również wybrany kontekst." },
  ],
  "Hanna Krall, Zdążyć przed Panem Bogiem": [
    { nr: 59, temat: "Czy możliwe jest zachowanie godności w skrajnych sytuacjach?",
      zrodlo: "Omów zagadnienie na podstawie „Zdążyć przed Panem Bogiem” Hanny Krall. W swojej odpowiedzi uwzględnij również wybrany kontekst." },
    { nr: 60, temat: "Zagłada z perspektywy świadka i uczestnika wydarzeń w getcie.",
      zrodlo: "Omów zagadnienie na podstawie „Zdążyć przed Panem Bogiem” Hanny Krall. W swojej odpowiedzi uwzględnij również wybrany kontekst." },
    { nr: 61, temat: "Walka o życie z perspektywy wojennej i powojennej.",
      zrodlo: "Omów zagadnienie na podstawie „Zdążyć przed Panem Bogiem” Hanny Krall. W swojej odpowiedzi uwzględnij również wybrany kontekst." },
  ],
  "Albert Camus, Dżuma": [
    { nr: 62, temat: "Co skłania człowieka do poświęceń?",
      zrodlo: "Omów zagadnienie na podstawie „Dżumy” Alberta Camusa. W swojej odpowiedzi uwzględnij również wybrany kontekst." },
    { nr: 63, temat: "Człowiek wobec cierpienia i śmierci.",
      zrodlo: "Omów zagadnienie na podstawie „Dżumy” Alberta Camusa. W swojej odpowiedzi uwzględnij również wybrany kontekst." },
    { nr: 64, temat: "Czy możliwa jest przyjaźń w sytuacjach skrajnych?",
      zrodlo: "Omów zagadnienie na podstawie „Dżumy” Alberta Camusa. W swojej odpowiedzi uwzględnij również wybrany kontekst." },
    { nr: 65, temat: "Jakie postawy przyjmuje człowiek wobec zła?",
      zrodlo: "Omów zagadnienie na podstawie „Dżumy” Alberta Camusa. W swojej odpowiedzi uwzględnij również wybrany kontekst." },
  ],
  "George Orwell, Rok 1984": [
    { nr: 66, temat: "Czy możliwe jest zbudowanie doskonałego państwa?",
      zrodlo: "Omów zagadnienie na podstawie utworu „Rok 1984” George’a Orwella. W swojej odpowiedzi uwzględnij również wybrany kontekst." },
    { nr: 67, temat: "Jak zachować wolność w państwie totalitarnym?",
      zrodlo: "Omów zagadnienie na podstawie utworu „Rok 1984” George’a Orwella. W swojej odpowiedzi uwzględnij również wybrany kontekst." },
    { nr: 68, temat: "Znaczenie propagandy w państwie totalitarnym.",
      zrodlo: "Omów zagadnienie na podstawie utworu „Rok 1984” George’a Orwella. W swojej odpowiedzi uwzględnij również wybrany kontekst." },
    { nr: 69, temat: "Nowomowa jako sposób na ograniczenie wolności człowieka.",
      zrodlo: "Omów zagadnienie na podstawie utworu „Rok 1984” George’a Orwella. W swojej odpowiedzi uwzględnij również wybrany kontekst." },
  ],
  "Sławomir Mrożek, Tango": [
    { nr: 70, temat: "Bunt przeciwko porządkowi społecznemu.",
      zrodlo: "Omów zagadnienie na podstawie „Tanga” Sławomira Mrożka. W swojej odpowiedzi uwzględnij również wybrany kontekst." },
    { nr: 71, temat: "Konflikt pokoleń.",
      zrodlo: "Omów zagadnienie na podstawie „Tanga” Sławomira Mrożka. W swojej odpowiedzi uwzględnij również wybrany kontekst." },
    { nr: 72, temat: "Normy społeczne – ograniczają człowieka czy porządkują życie?",
      zrodlo: "Omów zagadnienie na podstawie „Tanga” Sławomira Mrożka. W swojej odpowiedzi uwzględnij również wybrany kontekst." },
  ],
  "Marek Nowakowski, Górą „Edek” (Prawo prerii)": [
    { nr: 73, temat: "W jakim celu autor nawiązuje w swoim tekście do innego tekstu?",
      zrodlo: "Omów zagadnienie na podstawie utworu „Górą «Edek»” Marka Nowakowskiego. W swojej odpowiedzi uwzględnij również wybrany kontekst." },
  ],
  "Andrzej Stasiuk, Miejsce (Opowieści galicyjskie)": [
    { nr: 74, temat: "Miejsca ważne w życiu człowieka.",
      zrodlo: "Omów zagadnienie na podstawie „Miejsca” Andrzeja Stasiuka. W swojej odpowiedzi uwzględnij również wybrany kontekst." },
  ],
  "Olga Tokarczuk, Profesor Andrews w Warszawie (Gra na wielu bębenkach)": [
    { nr: 75, temat: "Stan wojenny z perspektywy obcokrajowca.",
      zrodlo: "Omów zagadnienie na podstawie utworu „Profesor Andrews w Warszawie” Olgi Tokarczuk. W swojej odpowiedzi uwzględnij również wybrany kontekst." },
  ],
};
